# Generated by Django 4.2.4 on 2023-08-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм ID пользователя'),
        ),
    ]
